# permissions for end users to view limitadors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: limitador-viewer-role
rules:
- apiGroups:
  - limitador.3scale.net
  resources:
  - limitadors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - limitador.3scale.net
  resources:
  - limitadors/status
  verbs:
  - get
