# permissions for end users to edit limitadors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: limitador-editor-role
rules:
- apiGroups:
  - limitador.3scale.net
  resources:
  - limitadors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - limitador.3scale.net
  resources:
  - limitadors/status
  verbs:
  - get
