## Append samples you want in your CSV to this file as resources ##
resources:
- limitador_v1alpha1_ratelimit.yaml
- limitador_v1alpha1_limitador.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
